services:
  postgres:
    image: postgres:16-alpine
    container_name: inventario-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: inventario_db
      POSTGRES_USER: inventario_user
      POSTGRES_PASSWORD: inventario_pass
    ports:
      - "5433:5432"
    volumes:
      - inventario_pgdata:/var/lib/postgresql/data

volumes:
  inventario_pgdata: