# Server configuration
spring.application.name=inventario-api
server.port=8080

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://127.0.0.1:5433/inventario_db
spring.datasource.username=inventario_user
spring.datasource.password=inventario_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger (OpenAPI)
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs