spring.application.name=actividad-jpa

# Base de datos H2
spring.datasource.url=jdbc:h2:mem:productosdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuración JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
